# Generated by Django 3.2.4 on 2021-06-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.IntegerField(choices=[(0, 'System Notification'), (1, 'Project Invite'), (2, 'Session Invite'), (3, 'Session Comment Mention'), (4, 'Story Comment Mention'), (5, 'Story Update')]),
        ),
    ]
