# Generated by Django 3.2.4 on 2021-06-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_score'),
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInviteNotificationData',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_invite', serialize=False, to='notifications.notification', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='SessionInviteNotificationData',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='session_invite', serialize=False, to='notifications.notification', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotificationData',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='system', serialize=False, to='notifications.notification', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='StoryNotificationData',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story', serialize=False, to='notifications.notification', to_field='id')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='StoryCommentNotificationData',
            fields=[
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='story_comment', serialize=False, to='notifications.notification', to_field='id')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.storycomment', to_field='id')),
            ],
        ),
    ]
