# Generated by Django 3.2.4 on 2021-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planningsessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='point',
            field=models.IntegerField(choices=[(0, 'Pass'), (1, '1/2'), (2, '1'), (3, '2'), (4, '3'), (5, '5'), (6, '8'), (7, '13')]),
        ),
    ]
