# Generated by Django 3.2.4 on 2021-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
