# Generated by Django 3.2.4 on 2021-06-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='after_story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='before_story',
        ),
        migrations.AddField(
            model_name='story',
            name='next_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_next_story', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='prev_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_previous_story', to='stories.story'),
        ),
    ]
